/// Flutter icons Look_custom_icons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Look_custom_icons
///      fonts:
///       - asset: fonts/Look_custom_icons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class Look_custom_icons {
  Look_custom_icons._();

  static const _kFontFam = 'Look_custom_icons';
  static const String? _kFontPkg = null;

  static const IconData cards = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cards_outline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outfit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData outfit_outline = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
